-- ============================================================================
-- NITTO LEGENDS PERFECT SUPABASE SCHEMA
-- ============================================================================
-- This schema is optimized for the Nitto Legends game server
-- Includes all necessary tables, indexes, triggers, and RLS policies
-- ============================================================================

-- Enable UUID extension for session keys
create extension if not exists "uuid-ossp";

-- ============================================================================
-- CORE TABLES
-- ============================================================================

-- Players table - stores all player account data
create table if not exists public.game_players (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  
  -- Currency and progression
  money bigint not null default 50000,
  points bigint not null default 1000000,
  score bigint not null default 0,
  
  -- Profile
  image_id integer not null default 0,
  gender text not null default 'm' check (gender in ('m', 'f')),
  driver_text text not null default '',
  
  -- Status flags
  active integer not null default 1,
  vip integer not null default 0,
  facebook_connected integer not null default 0,
  alert_flag integer not null default 0,
  
  -- Progression
  blackcard_progress integer not null default 0,
  sponsor_rating integer not null default 0,
  respect_level integer not null default 0,
  title_id integer not null default 0,
  track_rank integer not null default 0,
  
  -- Location and UI
  location_id integer not null default 100,
  background_id integer not null default 0,
  
  -- Messaging
  message_badge integer not null default 0,
  
  -- Team (nullable - player may not be in a team)
  team_id bigint,
  team_name text not null default '',
  
  -- Badges (stored as JSON array)
  badges_json jsonb not null default '[]'::jsonb,
  
  -- Default car reference
  default_car_game_id bigint,
  
  -- Role-based access control (5 = normal player, lower = admin)
  client_role integer not null default 5,
  
  -- Timestamps
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

-- Sessions table - tracks active player sessions
create table if not exists public.game_sessions (
  session_key text primary key,
  player_id bigint not null references public.game_players(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  last_seen_at timestamptz not null default timezone('utc', now())
);

-- Add expires_at column if it doesn't exist
alter table public.game_sessions 
  add column if not exists expires_at timestamptz not null default timezone('utc', now()) + interval '7 days';

-- Cars table - stores player-owned vehicles
create table if not exists public.game_cars (
  game_car_id bigint generated by default as identity primary key,
  player_id bigint not null references public.game_players(id) on delete cascade,
  
  -- Car identity
  catalog_car_id integer not null,
  selected boolean not null default false,
  
  -- Customization
  paint_index integer not null default 4,
  color_code text not null default 'C0C0C0',
  plate_name text not null default '',
  
  -- Visual state
  locked integer not null default 0,
  aero integer not null default 0,
  image_index integer not null default 0,
  
  -- Parts and wheels (stored as XML)
  wheel_xml text not null default '<ws><w wid=''1'' id=''1001'' ws=''17''/></ws>',
  parts_xml text not null default '',

  -- Test-drive state
  test_drive_invitation_id bigint,
  test_drive_name text,
  test_drive_money_price bigint,
  test_drive_point_price bigint,
  test_drive_expires_at timestamptz,
  
  -- Timestamps
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.game_cars add column if not exists test_drive_invitation_id bigint;
alter table public.game_cars add column if not exists test_drive_name text;
alter table public.game_cars add column if not exists test_drive_money_price bigint;
alter table public.game_cars add column if not exists test_drive_point_price bigint;
alter table public.game_cars add column if not exists test_drive_expires_at timestamptz;

-- Add unique partial index for one selected car per player
create unique index if not exists idx_game_cars_one_selected_per_player 
  on public.game_cars(player_id) 
  where selected = true;

-- Teams table - stores team/crew data
create table if not exists public.game_teams (
  id bigint generated by default as identity primary key,
  name text not null unique,
  tag text not null default '',
  description text not null default '',
  
  -- Team owner
  owner_player_id bigint references public.game_players(id) on delete set null,
  
  -- Customization
  avatar_path text not null default '',
  location_id integer not null default 100,
  
  -- Stats
  score bigint not null default 0,
  wins integer not null default 0,
  losses integer not null default 0,
  member_count integer not null default 0,
  
  -- Timestamps
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

-- Team members table - tracks team membership
create table if not exists public.game_team_members (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.game_teams(id) on delete cascade,
  player_id bigint not null references public.game_players(id) on delete cascade,
  
  -- Member role
  role text not null default 'member' check (role in ('owner', 'admin', 'member')),
  
  -- Contribution tracking
  contribution_score bigint not null default 0,
  
  -- Timestamps
  joined_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  
  -- Constraints
  unique (team_id, player_id),
  unique (player_id) -- Player can only be in one team
);

-- Mail table - stores in-game messages
create table if not exists public.game_mail (
  id bigint generated by default as identity primary key,
  recipient_player_id bigint not null references public.game_players(id) on delete cascade,
  sender_player_id bigint references public.game_players(id) on delete set null,
  
  -- Message organization
  folder text not null default 'inbox' check (folder in ('inbox', 'sent', 'trash')),
  message_type text not null default 'player' check (message_type in ('system', 'player', 'team')),
  
  -- Content
  subject text not null default '',
  body text not null default '',
  
  -- Status
  is_read boolean not null default false,
  is_deleted boolean not null default false,
  
  -- Attachments
  attachment_money bigint not null default 0,
  attachment_points bigint not null default 0,
  
  -- Timestamps
  created_at timestamptz not null default timezone('utc', now()),
  read_at timestamptz
);

-- ============================================================================
-- ADDITIONAL TABLES (Optional - for future features)
-- ============================================================================

-- Race history table - tracks completed races
create table if not exists public.game_race_history (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.game_players(id) on delete cascade,
  opponent_player_id bigint references public.game_players(id) on delete set null,
  
  -- Race details
  race_type text not null check (race_type in ('practice', 'quick', 'pink_slip', 'team')),
  track_id integer not null,
  
  -- Results
  won boolean not null,
  time_ms integer not null,
  money_won bigint not null default 0,
  points_won bigint not null default 0,
  
  -- Car used
  car_id bigint references public.game_cars(game_car_id) on delete set null,
  
  -- Timestamp
  raced_at timestamptz not null default timezone('utc', now())
);

-- Garage parts inventory - tracks owned parts not installed on cars
create table if not exists public.game_parts_inventory (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.game_players(id) on delete cascade,
  
  -- Part details
  part_catalog_id integer not null,
  quantity integer not null default 1,
  
  -- Timestamps
  acquired_at timestamptz not null default timezone('utc', now()),
  
  -- Constraints
  unique (player_id, part_catalog_id)
);

-- Transactions log - audit trail for money/points changes
create table if not exists public.game_transactions (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.game_players(id) on delete cascade,
  
  -- Transaction details
  transaction_type text not null check (transaction_type in ('race_win', 'race_loss', 'purchase', 'sale', 'gift', 'admin')),
  money_change bigint not null default 0,
  points_change bigint not null default 0,
  
  -- Context
  description text not null default '',
  reference_id bigint, -- Could reference race_id, car_id, etc.
  
  -- Timestamp
  created_at timestamptz not null default timezone('utc', now())
);

-- ============================================================================
-- FOREIGN KEY CONSTRAINTS (Added after tables exist to avoid circular dependencies)
-- ============================================================================

-- Add team_id column if it doesn't exist, then add foreign key
alter table public.game_players add column if not exists team_id bigint;

-- Drop existing constraint if it exists, then add it
alter table public.game_players drop constraint if exists game_players_team_id_fkey;
alter table public.game_players
  add constraint game_players_team_id_fkey
  foreign key (team_id) references public.game_teams(id) on delete set null;

-- ============================================================================
-- INDEXES FOR PERFORMANCE
-- ============================================================================

-- Players indexes
create index if not exists idx_game_players_username on public.game_players(username);
create index if not exists idx_game_players_team_id on public.game_players(team_id);

-- Sessions indexes
create index if not exists idx_game_sessions_player_id on public.game_sessions(player_id);

-- Only create expires_at index if column exists
create index if not exists idx_game_sessions_expires_at on public.game_sessions(expires_at);

-- Cars indexes
create index if not exists idx_game_cars_player_id on public.game_cars(player_id);
create index if not exists idx_game_cars_selected on public.game_cars(player_id, selected) where selected = true;

-- Team members indexes
create index if not exists idx_game_team_members_team_id on public.game_team_members(team_id);
create index if not exists idx_game_team_members_player_id on public.game_team_members(player_id);

-- Mail indexes
create index if not exists idx_game_mail_recipient on public.game_mail(recipient_player_id, folder, is_read, is_deleted, created_at desc);
create index if not exists idx_game_mail_sender on public.game_mail(sender_player_id);

-- Race history indexes (if using)
create index if not exists idx_game_race_history_player on public.game_race_history(player_id, raced_at desc);
create index if not exists idx_game_race_history_opponent on public.game_race_history(opponent_player_id);

-- Parts inventory indexes (if using)
create index if not exists idx_game_parts_inventory_player on public.game_parts_inventory(player_id);

-- Transactions indexes (if using)
create index if not exists idx_game_transactions_player on public.game_transactions(player_id, created_at desc);

-- ============================================================================
-- TRIGGERS FOR AUTO-UPDATING TIMESTAMPS
-- ============================================================================

-- Function to update updated_at timestamp
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

-- Apply triggers to all tables with updated_at
drop trigger if exists game_players_touch_updated_at on public.game_players;
create trigger game_players_touch_updated_at
  before update on public.game_players
  for each row execute function public.touch_updated_at();

drop trigger if exists game_cars_touch_updated_at on public.game_cars;
create trigger game_cars_touch_updated_at
  before update on public.game_cars
  for each row execute function public.touch_updated_at();

drop trigger if exists game_teams_touch_updated_at on public.game_teams;
create trigger game_teams_touch_updated_at
  before update on public.game_teams
  for each row execute function public.touch_updated_at();

drop trigger if exists game_team_members_touch_updated_at on public.game_team_members;
create trigger game_team_members_touch_updated_at
  before update on public.game_team_members
  for each row execute function public.touch_updated_at();

-- ============================================================================
-- FUNCTIONS FOR COMMON OPERATIONS
-- ============================================================================

-- Function to clean up expired sessions
create or replace function public.cleanup_expired_sessions()
returns integer
language plpgsql
as $$
declare
  deleted_count integer;
begin
  delete from public.game_sessions
  where expires_at < timezone('utc', now());
  
  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;

-- Function to update team member count
create or replace function public.update_team_member_count()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' then
    update public.game_teams
    set member_count = member_count + 1
    where id = new.team_id;
  elsif tg_op = 'DELETE' then
    update public.game_teams
    set member_count = member_count - 1
    where id = old.team_id;
  end if;
  return null;
end;
$$;

-- Apply trigger for team member count
drop trigger if exists game_team_members_update_count on public.game_team_members;
create trigger game_team_members_update_count
  after insert or delete on public.game_team_members
  for each row execute function public.update_team_member_count();

-- ============================================================================
-- ROW LEVEL SECURITY (RLS) - Optional but recommended
-- ============================================================================

-- Enable RLS on all tables
alter table public.game_players enable row level security;
alter table public.game_sessions enable row level security;
alter table public.game_cars enable row level security;
alter table public.game_teams enable row level security;
alter table public.game_team_members enable row level security;
alter table public.game_mail enable row level security;

-- Service role bypass (for backend server)
-- Drop existing policies if they exist, then recreate
drop policy if exists "Service role has full access to players" on public.game_players;
create policy "Service role has full access to players"
  on public.game_players
  for all
  using (true)
  with check (true);

drop policy if exists "Service role has full access to sessions" on public.game_sessions;
create policy "Service role has full access to sessions"
  on public.game_sessions
  for all
  using (true)
  with check (true);

drop policy if exists "Service role has full access to cars" on public.game_cars;
create policy "Service role has full access to cars"
  on public.game_cars
  for all
  using (true)
  with check (true);

drop policy if exists "Service role has full access to teams" on public.game_teams;
create policy "Service role has full access to teams"
  on public.game_teams
  for all
  using (true)
  with check (true);

drop policy if exists "Service role has full access to team members" on public.game_team_members;
create policy "Service role has full access to team members"
  on public.game_team_members
  for all
  using (true)
  with check (true);

drop policy if exists "Service role has full access to mail" on public.game_mail;
create policy "Service role has full access to mail"
  on public.game_mail
  for all
  using (true)
  with check (true);

-- ============================================================================
-- SAMPLE DATA (Optional - for testing)
-- ============================================================================

-- Insert test accounts
insert into public.game_players (
  username,
  password_hash,
  money,
  points,
  score,
  driver_text,
  vip,
  location_id
) values
  (
    'Tester1',
    'ecd71870d1963316a97e3ac3408c9835ad8cf0f3c1bc703527c30265534f75ae', -- password: 123456
    50000,
    1000000,
    0,
    'Test Account',
    0,
    100
  ),
  (
    'Admin',
    '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', -- password: 123456
    5000000,
    5000000,
    999999,
    'Administrator',
    1,
    500
  )
on conflict (username) do nothing;

-- ============================================================================
-- MAINTENANCE QUERIES
-- ============================================================================

-- To clean up expired sessions, run periodically:
-- select public.cleanup_expired_sessions();

-- To view player stats:
-- select username, money, points, score, location_id 
-- from public.game_players 
-- order by score desc limit 10;

-- To view active sessions:
-- select s.session_key, p.username, s.last_seen_at
-- from public.game_sessions s
-- join public.game_players p on p.id = s.player_id
-- where s.expires_at > now()
-- order by s.last_seen_at desc;

-- ============================================================================
-- NOTES
-- ============================================================================
-- 1. Use SUPABASE_SERVICE_ROLE_KEY for backend connections (bypasses RLS)
-- 2. Session cleanup should run periodically (cron job or scheduled function)
-- 3. parts_xml and wheel_xml are stored as text (XML format) for compatibility
-- 4. Money and points use bigint to prevent overflow
-- 5. All timestamps are in UTC
-- 6. The schema supports future features like race history and parts inventory
-- ============================================================================
