create table if not exists public.game_players (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  money bigint not null default 5000000,
  points bigint not null default 5000000,
  score bigint not null default 37420,
  image_id integer not null default 0,
  active integer not null default 1,
  vip integer not null default 0,
  facebook_connected integer not null default 0,
  alert_flag integer not null default 1,
  blackcard_progress integer not null default 1,
  sponsor_rating integer not null default 1,
  driver_text text not null default '',
  team_name text not null default '',
  gender integer not null default 0,
  respect_level integer not null default 0,
  message_badge integer not null default 0,
  badges_json jsonb not null default '[]'::jsonb,
  title_id integer not null default 1,
  track_rank integer not null default 3,
  location_id integer not null default 500,
  background_id integer not null default 1,
  default_car_game_id bigint,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.game_sessions (
  session_key text primary key,
  player_id bigint not null references public.game_players(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  last_seen_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.game_cars (
  account_car_id bigint generated by default as identity primary key,
  game_car_id bigint not null unique,
  player_id bigint not null references public.game_players(id) on delete cascade,
  catalog_car_id integer not null,
  selected boolean not null default false,
  paint_index integer not null default 4,
  plate_name text not null default '',
  locked integer not null default 0,
  aero integer not null default 0,
  color_code text not null default 'C0C0C0',
  image_index integer not null default 0,
  wheel_xml text not null default '',
  parts_xml text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.game_teams (
  id bigint generated by default as identity primary key,
  name text not null unique,
  tag text not null default '',
  description text not null default '',
  owner_player_id bigint references public.game_players(id) on delete set null,
  avatar_path text not null default '',
  location_id integer not null default 100,
  score bigint not null default 0,
  wins integer not null default 0,
  losses integer not null default 0,
  member_count integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.game_team_members (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.game_teams(id) on delete cascade,
  player_id bigint not null references public.game_players(id) on delete cascade,
  role text not null default 'member',
  contribution_score bigint not null default 0,
  joined_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (team_id, player_id),
  unique (player_id)
);

create table if not exists public.game_mail (
  id bigint generated by default as identity primary key,
  recipient_player_id bigint not null references public.game_players(id) on delete cascade,
  sender_player_id bigint references public.game_players(id) on delete set null,
  folder text not null default 'inbox',
  message_type text not null default 'system',
  subject text not null default '',
  body text not null default '',
  is_read boolean not null default false,
  is_deleted boolean not null default false,
  attachment_money bigint not null default 0,
  attachment_points bigint not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  read_at timestamptz
);

alter table public.game_players
add column if not exists team_id bigint references public.game_teams(id) on delete set null;

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists game_players_touch_updated_at on public.game_players;
create trigger game_players_touch_updated_at
before update on public.game_players
for each row execute procedure public.touch_updated_at();

drop trigger if exists game_cars_touch_updated_at on public.game_cars;
create trigger game_cars_touch_updated_at
before update on public.game_cars
for each row execute procedure public.touch_updated_at();

drop trigger if exists game_teams_touch_updated_at on public.game_teams;
create trigger game_teams_touch_updated_at
before update on public.game_teams
for each row execute procedure public.touch_updated_at();

drop trigger if exists game_team_members_touch_updated_at on public.game_team_members;
create trigger game_team_members_touch_updated_at
before update on public.game_team_members
for each row execute procedure public.touch_updated_at();

create index if not exists idx_game_sessions_player_id
on public.game_sessions(player_id);

create index if not exists idx_game_cars_player_id
on public.game_cars(player_id);

create index if not exists idx_game_players_team_id
on public.game_players(team_id);

create index if not exists idx_game_team_members_team_id
on public.game_team_members(team_id);

create index if not exists idx_game_mail_recipient_folder
on public.game_mail(recipient_player_id, folder, is_read, is_deleted, created_at desc);

-- Optional local sample accounts. These stay fully live-native:
-- no forced legacy public IDs, no Bean team seed, and no hardcoded team rows.

insert into public.game_players (
  username,
  password_hash,
  money,
  points,
  score,
  driver_text,
  team_name,
  vip,
  alert_flag,
  title_id,
  track_rank,
  location_id,
  default_car_game_id
) values
  (
    'Tester1',
    'ecd71870d1963316a97e3ac3408c9835ad8cf0f3c1bc703527c30265534f75ae',
    500000,
    50000,
    10000,
    '',
    '',
    1,
    0,
    0,
    0,
    500,
    1
  ),
  (
    'Oblong',
    '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92',
    500000,
    50000,
    691337420,
    'Admin rebuild',
    '',
    1,
    1,
    1,
    3,
    500,
    2
  )
on conflict (username) do update set
  password_hash = excluded.password_hash,
  money = excluded.money,
  points = excluded.points,
  score = excluded.score,
  driver_text = excluded.driver_text,
  team_name = excluded.team_name,
  vip = excluded.vip,
  alert_flag = excluded.alert_flag,
  title_id = excluded.title_id,
  track_rank = excluded.track_rank,
  location_id = excluded.location_id,
  default_car_game_id = excluded.default_car_game_id;

do $$
declare
  tester_id bigint;
  oblong_id bigint;
begin
  select id into tester_id from public.game_players where username = 'Tester1';
  select id into oblong_id from public.game_players where username = 'Oblong';

  if tester_id is not null then
    insert into public.game_cars (
      game_car_id,
      player_id,
      catalog_car_id,
      selected,
      paint_index,
      plate_name,
      locked,
      aero,
      color_code,
      image_index,
      wheel_xml,
      parts_xml
    ) values (
      1,
      tester_id,
      101,
      true,
      4,
      'TEST1',
      0,
      0,
      'FFFFFF',
      0,
      '<ws><w wid=''1'' id=''1001'' ws=''17''/></ws>',
      '<ps><p cd=''FFFFFF''/></ps>'
    )
    on conflict (game_car_id) do update set
      player_id = excluded.player_id,
      catalog_car_id = excluded.catalog_car_id,
      selected = excluded.selected,
      paint_index = excluded.paint_index,
      plate_name = excluded.plate_name,
      locked = excluded.locked,
      aero = excluded.aero,
      color_code = excluded.color_code,
      image_index = excluded.image_index,
      wheel_xml = excluded.wheel_xml,
      parts_xml = excluded.parts_xml;

    update public.game_players
    set default_car_game_id = 1, team_name = ''
    where id = tester_id;
  end if;

  if oblong_id is not null then
    insert into public.game_cars (
      game_car_id,
      player_id,
      catalog_car_id,
      selected,
      paint_index,
      plate_name,
      locked,
      aero,
      color_code,
      image_index,
      wheel_xml,
      parts_xml
    ) values
      (
        2,
        oblong_id,
        2,
        true,
        4,
        'OBLONG',
        0,
        0,
        'CC0000',
        0,
        '<ws><w wid=''1'' id=''1001'' ws=''17''/></ws>',
        '<ps><p cd=''CC0000''/></ps>'
      ),
      (
        3,
        oblong_id,
        3,
        false,
        4,
        'ADMIN',
        0,
        0,
        'FFFFFF',
        0,
        '<ws><w wid=''1'' id=''1001'' ws=''17''/></ws>',
        '<ps><p cd=''FFFFFF''/></ps>'
      )
    on conflict (game_car_id) do update set
      player_id = excluded.player_id,
      catalog_car_id = excluded.catalog_car_id,
      selected = excluded.selected,
      paint_index = excluded.paint_index,
      plate_name = excluded.plate_name,
      locked = excluded.locked,
      aero = excluded.aero,
      color_code = excluded.color_code,
      image_index = excluded.image_index,
      wheel_xml = excluded.wheel_xml,
      parts_xml = excluded.parts_xml;

    update public.game_players
    set default_car_game_id = 2, team_name = ''
    where id = oblong_id;
  end if;
end $$;
